Repository FirebirdSQL/firebird, pull requests merged in 2022-12, with the labels that each got.

#7399 Simplify client library build
  builds/install/arch-specific/freebsd/install.sh.in
  builds/install/arch-specific/linux/Makefile.in
  builds/install/arch-specific/linux/makeInstallImage.sh.in
  builds/mac_os_x/CS/CS.pbproj/project.pbxproj
  builds/mac_os_x/CS/Helpers.make
  builds/mac_os_x/CS/gpre_wrapper.sh
  builds/mac_os_x/CS/make_wrapper.sh
  builds/mac_os_x/CS/stlport_vars.cpp
  builds/mac_os_x/CS/stub.c
  builds/posix/Makefile.in
  builds/posix/make.android.arm64
  builds/posix/make.android.arme
  builds/posix/make.android.x86
  builds/posix/make.android.x86_64
  builds/posix/make.defaults
  builds/win32/make_all.bat
  builds/win32/make_boot.bat
  builds/win32/msvc15/FirebirdCommon.props
  builds/win32/msvc15/common.vcxproj
  builds/win32/msvc15/engine.vcxproj
  builds/win32/msvc15/engine_test.vcxproj
  builds/win32/msvc15/fbtrace.vcxproj
  builds/win32/msvc15/gbak.vcxproj
  builds/win32/msvc15/yvalve.vcxproj
  builds/win32/msvc15/yvalve.vcxproj.filters
  builds/win32/preprocess.bat
  builds/win32/run_all.bat
  builds/win32/setenvvar.bat
  configure.ac
  src/common/classes/RefCounted.h
  src/include/firebird/Message.h
  src/yvalve/array.cpp
  src/yvalve/array_proto.h
  src/yvalve/blob.cpp
  src/yvalve/blob_proto.h
  src/yvalve/why.cpp
Labels: component: build issues / porting, type: improvement, fix-version: 5.0 Beta 1

#281 RDB$BLOB_UTIL system package.
  builds/win32/msvc15/engine_static.vcxproj
  builds/win32/msvc15/engine_static.vcxproj.filters
  doc/sql.extensions/README.blob_util.md
  src/include/firebird/impl/msg/jrd.h
  src/include/gen/Firebird.pas
  src/jrd/BlobUtil.cpp
  src/jrd/BlobUtil.h
  src/jrd/SystemPackages.cpp
  src/jrd/fields.h
  src/jrd/jrd.h
  src/jrd/names.h
  src/jrd/tra.cpp
  src/jrd/tra.h
Labels: type: improvement

#7390 Fix invariants optimization involving views (#7388)
  src/dsql/ExprNodes.cpp
Labels: component: engine, type: bug, fix-version: 5.0 Beta 1
