Repository FirebirdSQL/firebird, pull requests merged in 2023-08, with the labels that each got.

#7694 Fix false positives of "missing entries for record X" error during index validation when a deleted record version is committed and has a backversion
  src/jrd/validation.cpp
Labels: type: bug, component: gfix, affect-version: 3.0.10, affect-version: 4.0.2, affect-version: 5.0 Beta 1

#7689 Document possible problem of very high overhead using the profiler.
  doc/sql.extensions/README.profiler.md
Labels: component: documentation, type: task, affect-version: 5.0 Initial, affect-version: 5.0 Beta 1

#7466 Add COMPILE trace events for procedures/functions/triggers
  src/include/firebird/FirebirdInterface.idl
  src/include/firebird/IdlFbInterfaces.h
  src/include/gen/Firebird.pas
  src/jrd/Function.epp
  src/jrd/exe.cpp
  src/jrd/jrd.cpp
  src/jrd/met.epp
  src/jrd/trace/TraceJrdHelpers.h
  src/jrd/trace/TraceManager.cpp
  src/jrd/trace/TraceManager.h
  src/jrd/trace/TraceObjects.cpp
  src/jrd/trace/TraceObjects.h
  src/utilities/ntrace/TracePluginImpl.cpp
  src/utilities/ntrace/TracePluginImpl.h
  src/utilities/ntrace/fbtrace.conf
  src/utilities/ntrace/paramtable.h
Labels: component: engine, type: improvement, component: tracemgr, fix-version: 5.0 Beta 2

#7714 Fixed bug #7713
  src/dsql/ExprNodes.cpp
  src/jrd/exe.h
  src/jrd/met.epp
Labels: type: bug, affect-version: 3.0.0, affect-version: 4.0.0, affect-version: 5.0 Initial
