Repository FirebirdSQL/firebird, pull requests merged in 2023-09, with the labels that each got.

#7707 Better processing and optimization if IN <list> predicates
  src/dsql/BoolNodes.cpp
  src/dsql/BoolNodes.h
  src/dsql/DdlNodes.epp
  src/dsql/ExprNodes.cpp
  src/dsql/Nodes.h
  src/dsql/parse.y
  src/include/firebird/impl/blr.h
  src/jrd/RecordSourceNodes.cpp
  src/jrd/blp.h
  src/jrd/btr.cpp
  src/jrd/btr.h
  src/jrd/btr_proto.h
  src/jrd/optimizer/Optimizer.h
  src/jrd/optimizer/Retrieval.cpp
  src/jrd/recsrc/IndexTableScan.cpp
  src/jrd/recsrc/RecordSource.cpp
  src/jrd/recsrc/RecordSource.h
  src/jrd/val.h
  src/yvalve/gds.cpp
Labels: type: improvement, fix-version: 5.0 Beta 2

#7426 Ensure the DDL trigger requests are cached
  src/jrd/exe.cpp
Labels: component: engine, type: bug

#7735 Per-attachment cache of pointers to the often used page buffers.
  builds/win32/msvc15/engine_static.vcxproj
  builds/win32/msvc15/engine_static.vcxproj.filters
  src/jrd/Attachment.h
  src/jrd/PageToBufferMap.h
  src/jrd/cch.cpp
Labels: type: improvement

#7747 Fix an issue where the garbage collection in indexes and blobs is not performed in VIO_backout
  src/jrd/Record.h
  src/jrd/Savepoint.cpp
  src/jrd/idx.cpp
  src/jrd/tra.h
  src/jrd/vio.cpp
Labels: component: engine, type: bug, affect-version: 5.0 Beta 1, affect-version: 3.0.11, affect-version: 4.0.3

#7617 SQL 2023 ANY_VALUE aggregate function.
  doc/sql.extensions/README.aggregate_functions.md
  src/common/ParserTokens.h
  src/dsql/AggNodes.cpp
  src/dsql/AggNodes.h
  src/dsql/parse.y
Labels: component: engine, type: new feature, fix-version: 6.0 Beta 1

#7557 Named arguments, DEFAULT in argument list and CALL statement
  doc/sql.extensions/README.call.md
  doc/sql.extensions/README.named_arguments.md
  src/common/ParserTokens.h
  src/common/classes/GenericMap.h
  src/common/classes/array.h
  src/dsql/ExprNodes.cpp
  src/dsql/ExprNodes.h
  src/dsql/Nodes.h
  src/dsql/StmtNodes.cpp
  src/dsql/StmtNodes.h
  src/dsql/dsql.cpp
  src/dsql/dsql.h
  src/dsql/gen.cpp
  src/dsql/gen_proto.h
  src/dsql/metd.epp
  src/dsql/parse.y
  src/dsql/pass1.cpp
  src/include/firebird/impl/blr.h
  src/include/firebird/impl/msg/jrd.h
  src/include/gen/Firebird.pas
  src/jrd/RecordSourceNodes.cpp
  src/jrd/RecordSourceNodes.h
  src/jrd/blp.h
  src/jrd/cmp.cpp
  src/jrd/cmp_proto.h
  src/jrd/dfw.epp
  src/jrd/irq.h
  src/jrd/met.epp
  src/jrd/par.cpp
  src/jrd/par_proto.h
  src/yvalve/gds.cpp
Labels: component: engine, type: new feature
