Repository FirebirdSQL/firebird, pull requests merged in 2023-05, with the labels that each got.

#7578 Change min macOS (Apple M1) deployment target to 11.0
  builds/posix/prefix.darwin_aarch64
Labels: component: build issues / porting, type: improvement

#7559 Optimize creation of expression and partial indices
  src/jrd/btr.cpp
  src/jrd/btr.h
  src/jrd/btr_proto.h
  src/jrd/idx.cpp
  src/jrd/met.epp
  src/jrd/recsrc/IndexTableScan.cpp
  src/jrd/replication/Applier.cpp
  src/jrd/validation.cpp
  src/jrd/validation.h
Labels: component: engine, type: improvement

#7577 Allow nested parenthesized joined table
  src/dsql/parse.y
Labels: component: engine, type: improvement, fix-version: 5.0 Beta 2
