Repository FirebirdSQL/firebird, pull requests merged in 2023-12, with the labels that each got.

#7910 Add backward compatibility option that disables joins transformation
  src/common/config/config.h
  src/jrd/RecordSourceNodes.cpp
Labels: component: engine, type: improvement, fix-version: 5.0 RC 2

#7918 Allow to configure Firebird in posix using relative directories with options --with-fb*
  configure.ac
  src/common/TimeZoneUtil.cpp
  src/common/utils.cpp
  src/yvalve/gds.cpp
Labels: component: build issues / porting, type: improvement

#7853 Do not consider non-deterministic expressions as invariants in pre-filters
  src/dsql/ExprNodes.cpp
  src/dsql/ExprNodes.h
  src/dsql/Nodes.h
  src/jrd/RecordSourceNodes.h
  src/jrd/SysFunction.cpp
  src/jrd/SysFunction.h
  src/jrd/optimizer/Optimizer.cpp
Labels: component: engine, type: bug, affect-version: 5.0 Beta 1, affect-version: 5.0 RC 1, fix-version: 5.0 RC 2
