Repository FirebirdSQL/firebird, pull requests merged in 2024-11, with the labels that each got.

#8310 Collect network statistics and make it available for the user applications.
  doc/README.isql_enhancements.txt
  src/include/firebird/impl/inf_pub.h
  src/include/gen/Firebird.pas
  src/isql/isql.epp
  src/isql/isql.h
  src/isql/show.epp
  src/remote/client/interface.cpp
  src/remote/inet.cpp
  src/remote/os/win32/xnet.cpp
  src/remote/protocol.cpp
  src/remote/remote.cpp
  src/remote/remote.h
Labels: type: improvement

#8316 Cost-based decision between ORDER and SORT plans
  src/jrd/optimizer/Optimizer.cpp
  src/jrd/optimizer/Optimizer.h
  src/jrd/optimizer/Retrieval.cpp
Labels: component: engine, type: improvement, fix-version: 6.0 Alpha 1, red-soft

#8319 Use a 64bit counter for the records written during the backup
  src/burp/BurpTasks.cpp
Labels: type: bug, component: gbak, priority: minor, fix-version: 5.0.2

#8324 Make asynchronous replica re-initialization reliable
  src/remote/server/ReplServer.cpp
Labels: priority: major, type: bug, affect-version: 4.0.0, component: replication, affect-version: 4.0.1, affect-version: 4.0.2, affect-version: 4.0.3, affect-version: 6.0 Initial, affect-version: 4.0.4, affect-version: 5.0.0, fix-version: 5.0.2, affect-version: 5.0.1, affect-version: 4.0.5
