Repository FirebirdSQL/firebird, pull requests merged in 2024-02, with the labels that each got.

#7987 Solution for #7568: Equivalence of boolean condition in partial index
  src/dsql/BoolNodes.cpp
  src/dsql/ExprNodes.h
Labels: component: engine, type: improvement, fix-version: 6.0 Alpha 1

#7991 Some enhancements for the file open modes (FS cache usage and forced writes)
  src/jrd/Database.cpp
  src/jrd/Database.h
  src/jrd/jrd.cpp
  src/jrd/nbak.cpp
  src/jrd/nbak.h
  src/jrd/os/pio_proto.h
  src/jrd/os/posix/unix.cpp
  src/jrd/os/win32/winnt.cpp
  src/jrd/pag.cpp
  src/jrd/pag_proto.h
  src/jrd/sdw.cpp
Labels: type: improvement, type: cleanup

#7990 Encapsulate GUID operations
  src/common/os/guid.h
  src/common/os/posix/guid.cpp
  src/common/os/win32/guid.cpp
  src/common/os/win32/os_utils.cpp
  src/jrd/Database.cpp
  src/jrd/Database.h
  src/jrd/Monitoring.cpp
  src/jrd/SysFunction.cpp
  src/jrd/inf.cpp
  src/jrd/jrd.cpp
  src/jrd/nbak.cpp
  src/jrd/pag.cpp
  src/jrd/replication/ChangeLog.cpp
  src/jrd/replication/ChangeLog.h
  src/jrd/replication/Config.cpp
  src/jrd/replication/Config.h
  src/jrd/replication/Manager.cpp
  src/jrd/replication/Publisher.cpp
  src/jrd/trace/TraceService.cpp
  src/remote/server/ReplServer.cpp
  src/utilities/gstat/ppg.cpp
  src/utilities/nbackup/nbackup.cpp
Labels: type: cleanup

#7989 Improve performance of external (UDR) functions
  examples/udr/Functions.cpp
  src/dsql/ExprNodes.cpp
  src/dsql/Nodes.h
  src/jrd/ExtEngineManager.cpp
  src/jrd/ExtEngineManager.h
  src/jrd/Function.h
  src/jrd/exe.cpp
  src/jrd/exe.h
  src/jrd/exe_proto.h
  src/jrd/jrd.h
Labels: type: improvement
