Repository FirebirdSQL/firebird, pull requests merged in 2025-02, with the labels that each got.

#8318 Send small blobs inline.
  src/include/fb_types.h
  src/include/firebird/FirebirdInterface.idl
  src/include/firebird/IdlFbInterfaces.h
  src/include/firebird/impl/consts_pub.h
  src/include/firebird/impl/inf_pub.h
  src/include/gen/Firebird.pas
  src/jrd/EngineInterface.h
  src/jrd/jrd.cpp
  src/remote/client/interface.cpp
  src/remote/parser.cpp
  src/remote/protocol.cpp
  src/remote/protocol.h
  src/remote/remote.cpp
  src/remote/remote.h
  src/remote/server/server.cpp
  src/yvalve/YObjects.h
  src/yvalve/why.cpp
Labels: type: improvement

#8401 ODS14: header page refactoring
  src/common/classes/DbImplementation.cpp
  src/common/classes/DbImplementation.h
  src/jrd/CryptoManager.cpp
  src/jrd/Database.cpp
  src/jrd/Database.h
  src/jrd/Monitoring.cpp
  src/jrd/SysFunction.cpp
  src/jrd/cch.cpp
  src/jrd/constants.h
  src/jrd/idx.cpp
  src/jrd/jrd.cpp
  src/jrd/nbak.cpp
  src/jrd/nbak.h
  src/jrd/ods.cpp
  src/jrd/ods.h
  src/jrd/ods_proto.h
  src/jrd/os/posix/unix.cpp
  src/jrd/pag.cpp
  src/jrd/shut.cpp
  src/jrd/tpc.cpp
  src/jrd/tra.cpp
  src/jrd/trace/TraceObjects.h
  src/jrd/validation.cpp
  src/utilities/gstat/ppg.cpp
  src/utilities/nbackup/nbackup.cpp
  src/utilities/rebuild/rebuild.cpp
Labels: component: engine, type: task

#8340 Increase index flags capacity in ODS14
  src/jrd/btr.cpp
  src/jrd/btr.h
  src/jrd/idx.h
  src/jrd/ini.epp
  src/jrd/ods.h
  src/jrd/validation.cpp
  src/jrd/validation.h
  src/utilities/gstat/dba.epp
Labels: type: task

#8428 ODS14: Store (and return via *_LENGTH functions) blob length longer than 4GB
  src/dsql/ExprNodes.cpp
  src/jrd/blb.h
  src/jrd/ods.h
Labels: component: engine, type: improvement, fix-version: 6.0 Alpha 1

#8447 Avoid index scan for lower/upper bounds containing NULL keys
  src/jrd/btr.cpp
Labels: component: engine, type: improvement

#8446 Ignore NULLs (if desired) while scanning keys during index navigation
  src/jrd/btr.cpp
  src/jrd/recsrc/IndexTableScan.cpp
Labels: component: engine, type: improvement, fix-version: 6.0 Alpha 1
